name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  # - python=3.10.0
  - jupyterlab
  # - seaborn
  - pandas=1.2.4
  - pip=22.3.1
  - pandas-profiling=2.11.0
  # - pyarrow=2.0
  - pip:
      - wandb==0.13.9
