name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.1
  - matplotlib
  - pandas
  - git=2.30.2
  - pip=22.3.1
  - pip:
      - mlflow==2.1.1
      - wandb==0.13.9
      - protobuf==3.19.0