name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=1.5.2
  - scikit-learn=1.2
  - matplotlib=3.6.2
  - plotly=5.11.0
  - pillow=9.4.0
  - pip=22.3.1
  - pip:
      - wandb==0.13.9
      - setuptools==66.1.1
      - protobuf==3.19.0
      - omegaconf==2.2
      - mlflow==2.1.1
